import RootLayout from './clientLayout'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Sachin Jayadev: Portfolio',
  description: 'Generated by create next app',
}




export default function HomePage({children}: {
  children: React.ReactNode
}) {
  // Your page content here
  return (
    <RootLayout>
      {/* Your page content */}
      {children}
    </RootLayout>
  )
}